### ISSUE TITLE
Add an APE index

### ISSUE THREAD

**Issue by embray** [astropy/astropy-APEs#10]
If there is one already it would be good if it were linked to in the readme.  If there isn't, there should be (perhaps in the readme, or somewhere else).

**Comment by astrofrog** [comment]
Related: https://github.com/astropy/astropy.github.com/issues/30

**Comment by sudheesh001** [comment]
Does this have to be a new file that has to be added with the details as follows ?
```
================================================================================
index val | APE Title | author | date created | date-last-revised | type | status
================================================================================
```

Wouldn't it be better if we have the same information present as a `json` value instead so that it could also be used in astropy/astropy.github.com#30

```json
{
  "APE": [
    {
      "index": 1,
      "APE-Title": "Title of the APE",
      "author": [
        "Name of Author 1",
        "Name of Author 2"
      ],
      "date_created": "2015-02-16",
      "date_last_revised": "2015-02-16",
      "type": "String",
      "Status": "Status of APE"
    },
    {
      "index": 2,
      "APE-Title": "Title of the APE",
      "author": [
        "Name of Author 1",
        "Name of Author 2"
      ],
      "date_created": "2015-02-16",
      "date_last_revised": "2015-02-16",
      "type": "String",
      "Status": "Status of APE"
    }
  ]
}
```

**Comment by pllim** [comment]
:+1:  I keep forgetting what APE number is the one I want.

**Comment by taldcroft** [comment]
I have a +2" [APE index](https://en.wikipedia.org/wiki/Ape_index).

**Comment by evertrol** [comment]
Is this still an issue?
Would anyone mind if I manually create a restructured text or Markdown APE index file, and link that file from the README? Github will render it fine, and in reST form, it may be useful for including the docs as well.

Following Python's example, perhaps it should be numbered APE 0?
