### ISSUE TITLE
APE 18: Replace NEP 29 with SPEC 0

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-APEs#101]
As proposed by @bnavigator here:

* https://github.com/astropy/astropy/pull/16376

For reference:

* https://numpy.org/neps/nep-0029-deprecation_policy.html (I don't see any deprecation notice here though)
* https://scientific-python.org/specs/spec-0000/

**Comment by bnavigator** [comment]
> * (I don't see any deprecation notice here though)

It's the "Note" box right at the top.

> This NEP is superseded by the scientific python ecosystem coordination guideline [SPEC 0 — Minimum Supported Versions](https://scientific-python.org/specs/spec-0000/).

**Comment by pllim** [comment]
Oh, haha... I was blind...

**Comment by eerovaher** [comment]
APE 18 refers to NEP 29 which in turn refers to SPEC 0. So APE 18 is referring to SPEC 0 already, it's just doing it indirectly. I don't see why we shouldn't update APE 18 to refer to SPEC 0 directly.

**Comment by nstarman** [comment]
Should we go further and see if we can "endorse" SPEC 0 and get Astropy on its schedule?

**Comment by pllim** [comment]
I am not sure if Scientific Python is even looking for our endorsement. We are not one of the "core libraries" in their ecosystem.

**Comment by neutrinoceros** [comment]
Well it _could_ be argued that astropy is on par with`zarr` in terms of PyPI download stats: astropy gets ~40k downloads a day, `zarr` gets ~25k

**Comment by neutrinoceros** [comment]
(but zarr probably has much more room to grow)

**Comment by pllim** [comment]
I don't want to start that fire. Haha. astropy is very domain specific, unlike zarr. 😅

**Comment by pllim** [comment]
So it seems like the consensus is to update the APE but also I have not heard from the APE 18 authors. @Cadair and @astrofrog , what do you think?

**Comment by Cadair** [comment]
Good with me.

**Comment by pllim** [comment]
@bnavigator , are you still interested to update the link? But this time, it would be in https://github.com/astropy/astropy-APEs/blob/main/APE18.rst file instead in this repo. Thanks!

**Comment by bnavigator** [comment]
I am not sure if updating an accepted APE is the correct way. I originally wanted to update to whatsnew of Astropy 6.1 directly (https://github.com/astropy/astropy/pull/16376) and still think this would be more appropriate. 

I tend to side with https://github.com/astropy/astropy-APEs/issues/101#issuecomment-2096270409 for the APE and would  move to SPEC-0 for all future references (including whatsnews/changelogs)
> APE 18 refers to NEP 29 which in turn refers to SPEC 0. So APE 18 is referring to SPEC 0 already, it's just doing it indirectly. I don't see why we shouldn't update APE 18 to refer to SPEC 0 directly.
