### ISSUE TITLE
APE 18: Ownership of Zenodo should be transferred to Astropy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-APEs#108]
1. Find the actual owner of https://zenodo.org/records/4563083 for APE 18. cc @Cadair and @astrofrog as original APE authors.
2. Find a way to transfer it to Astropy Project account.
3. Update the record with #107

**Comment by Cadair** [comment]
Not it 😆

**Comment by pllim** [comment]
I contacted Zenodo and Zenodo is trying to contact the owner but won't tell me who this person is, so all we can do is wait.

**Comment by astrofrog** [comment]
Not me

**Comment by astrofrog** [comment]
Maybe @eteq?

**Comment by pllim** [comment]
Last modification of APAE 18 was dated 2021-Dec-25. At that time, I think CoCo was @kelle @mwcraig @hamogu @adrn @eteq (ref: https://github.com/astropy/astropy-project/blob/main/policies/coco-operating-policies.md)

**Comment by hamogu** [comment]
My bet is @eteq ... I know we discussed ownership at the time and there was a long-runnig (several years) todo list for @eteq to transfer all APEs that he's personally owned to astropy. However, that's been stuck in run-arounds with Zenodo for as long as I was on the coco.

**Comment by pllim** [comment]
Phew finally resolved for this one. I will update the record.

**Comment by eteq** [comment]
For the record, Zenodo support reached out to me several month back, I confirmed I was happy with them transferring ownership, and then it finally took effect like a week or two ago.  So it sounds like it just takes them time to get to it :shrug:
