### ISSUE TITLE
Update Zenodo guidelines

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-APEs#30]
I've uploaded an APE to Zenodo as a first test:

https://zenodo.org/record/1038587#.WfX5xkzGzBU

Note that all metadata can be updated, so it's fine if we decide to change things. Questions that came up:

* Upload type: Publication?
* Publication type: Technical note?
* If accepted and revised date disagrees, go with last revised date? (for APEs going forward we will upload on acceptance this is not relevant, but I'm just asking for past APEs)
* For past APEs, if there were revisions post-acceptance, should the GitHub URL for the alternate identifier be the last modified commit rather than merge commit?
* For the title, for anyone who stumbles across these documents in Zenodo, I think it would be clearer to have the title as:

**Astropy Proposal for Enhancement: Roadmap for Python 3-only support (APE 10)**

instead of

**APE 10: Roadmap for Python 3-only support**

Do you agree? I'm happy to update the guidelines but just wanted to check all this first.

cc @eteq @bsipocz

**Comment by eteq** [comment]
> Upload type: Publication?

👍 

> Publication type: Technical note?

👍 

> If accepted and revised date disagrees, go with last revised date? (for APEs going forward we will upload on acceptance this is not relevant, but I'm just asking for past APEs)

👍 

> For past APEs, if there were revisions post-acceptance, should the GitHub URL for the alternate identifier be the last modified commit rather than merge commit?

👍 

> For the title, for anyone who stumbles across these documents in Zenodo, I think it would be clearer to have the title as:

Maybe "*Astropy Proposal for Enhancement 10: Roadmap for Python 3-only support (APE 10)*" ? I slightly favor that (including the # before the colon as well), but either that or your suggestion works.

**Comment by bsipocz** [comment]
@astrofrog @eteq - all sounds good. I also like @eteq's suggestion, having the number at both places couldn't hurt.

**Comment by astrofrog** [comment]
Ok sounds good. I can try uploading all the APEs this week.

**Comment by astrofrog** [comment]
@eteq @bsipocz - thanks! Updated in https://github.com/astropy/astropy-APEs/pull/32
