### ISSUE TITLE
APE14: order of axes in pixel_shape

### ISSUE THREAD

**Issue by nden** [astropy/astropy-APEs#43]
What is the order of axes in `pixel_shape` and `pixel_bounds`? 
I suggest `Cartesian` or `FITS` order, i.e. `xyz` .

**Comment by astrofrog** [comment]
That might make sense to avoid confusion with existing WCS methods, but I agree this should be clarified in the APE. I've also been finding issues with things not being specified enough in the APE, so I'm going to try and make a list and set up a hangout to discuss them.

**Comment by astrofrog** [comment]
Resolved in https://github.com/astropy/astropy-APEs/pull/45
