### ISSUE TITLE
Update APE 14 on Zenodo

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-APEs#47]
APE 14 was recently updated, so we should upload a new version to Zenodo. This is a reminder to figure out who uploaded the original version, and a note that to update the version, the way to do it is to go to the existing record on Zenodo, and click on 'New version', remove the existing file and add a new file, and increment the version number and publication date.

**Comment by pllim** [comment]
Did this happen? This issue is now 4 years old.

**Comment by weaverba137** [comment]
Since we're discussing APE 14 *right now*, this is worth asking again.

**Comment by dhomeier** [comment]
So should the present version get its own record, and then upload a third version once the next revision is done?

**Comment by weaverba137** [comment]
Assuming the present version never did get its own record (I haven't actually checked yet), then yes.

**Comment by weaverba137** [comment]
Here is the link, https://zenodo.org/records/1188875

As far as I can tell there was only ever one version, dated 2018-02-28. 

The last *change* to APE 14 was 2018-11-14. And there were a lot of changes spread out between February & November 2018. So the actual version in GitHub is definitely non-trivially different from the version in Zenodo.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-APEs/issues/47#issuecomment-2160162128

Might have been an oversight. I think CoCo is responsible for uploading new versions as needed. Right, @eteq ?

**Comment by weaverba137** [comment]
Also note: the top-level README.rst file contains the old Zenodo link, so that will need to be updated.

**Comment by eteq** [comment]
Turns out the zenodo entry is associated with *my* account, not the Astropy one (this is an ongoing issue we're trying to resolve with Zenodo...) so I'll update it and close this when I have done so.

**Comment by eteq** [comment]
Alright, new version up at https://zenodo.org/records/11566733 - I'll make a PR to update the index and close this issue through that.
