### ISSUE TITLE
Update APE 10 to extend to Python 3.7 and beyond?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-APEs#51]
https://github.com/astropy/astropy-APEs/blob/master/APE10.rst only covers up to 3.6. But this is still too early but we need to do it eventually when Python 3.8, etc comes out.

**Comment by astrofrog** [comment]
I think we wrote it as a generalised rule so that we can figure it out for future releases automatically: _the Python 3.x versions supported by an Astropy release would be the versions supported by the Python developers_. So maybe no need to update the APE?

**Comment by pllim** [comment]
I guess I don't quite get the equation here then. Tentatively, Astropy 3.3 would be Nov/Dec 2019 and it drops Python 3.5 but Python 3.5's end-of-life is not till 2020-09-13 in https://devguide.python.org/#status-of-python-branches. So, we drop it in a release that happens about a year before end-of-life?

**Comment by bsipocz** [comment]
@pllim - 3.3 is not happening, it will be 4.0 which has a 2 year lifetime that goes beyond 2020.

**Comment by pllim** [comment]
Ak, ok. Thanks for the clarification!
