### ISSUE TITLE
APE 0 should be updated regarding Coordination Committee membership

### ISSUE THREAD

**Issue by eerovaher** [astropy/astropy-APEs#74]
This is what APE 0 has to say about the number of Coordination Committee members: 
https://github.com/astropy/astropy-APEs/blob/79242a8a0fa37fb10260952ca393bb88d1bfeac0/APE0.rst#L52-L54
The number is now known to be 5, so the text needs to be updated accordingly. Related to that, the first Coordination Committee terms were written out for four members and should be updated:
https://github.com/astropy/astropy-APEs/blob/79242a8a0fa37fb10260952ca393bb88d1bfeac0/APE0.rst#L156-L158

**Comment by pllim** [comment]
If I remember correctly, the "4 or 5" was intentional because if we happen not to have enough candidates for one year, then the CoCo is allowed to go back to 4. But other original authors could correct me if I remember wrong.

**Comment by eerovaher** [comment]
The APE says that the number of CoCo members was to be fixed at first election, so changing it is not permitted.

**Comment by eerovaher** [comment]
I don't know what the terms of the initial CoCo should be, so I don't see how I could open a pull request for updating that in the APE.
