### ISSUE TITLE
APE 0: Why must the returns officer be non-voting?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-APEs#75]
This essentially requires us to always find someone outside the astropy project, because all members that are deeply involved will be voting members. Alternatively, one member must abstain from voting, just to be able to be the returns officer.

I get the motivation for requiring the returns officer to be non-voting (don't want that person to meddle with the votes since no one else is looking), but 
- a technical solution such as helios would make the return's officer's vote just as anonymous as all other votes and that person (depending on the technical platform used for voting) would not have any special knowledge either
- just the requirement to be "non-voting" does not mean the returns officer is not conflicted e.g. they might really like or dislike some candidate. If this provision is meant to prevent tampering with the votes, that "non-voting" is not enough, we need a "not involved" returns officer.

So, I suggest to either remove the "non-voting" requirement to change it to "who cannot be a voting member and not have personally ties to any candidate".

**Comment by Cadair** [comment]
To be clear, this is for the CoCo election?

**Comment by hamogu** [comment]
Yes. I've tried to think about who a good returns officer might be, but I don't think it's fair to ask anyone from our community to give up their right to vote to fill this role. 

Note that my suggestion is not official Coco policy, I'm just wondering personally why "non-voting" was put in there and if it would be better to change it to something else.

**Comment by pllim** [comment]
Wanna propose a PR? https://github.com/astropy/astropy-APEs/blob/main/APE1.rst#modifications-to-an-ape

**Comment by hamogu** [comment]
We talked to NumFOCUS and they are happy to be our returns officer. If we can continue that going forward, that's better because it's more neutral, so I opt to not doing a change right now. (Also, it's confusing to have that at the the time as the Coco election.) We can always revisit later if we have to.
