### ISSUE TITLE
Is APE 13 still considered "current"? (Yes, but not the viz tool part)

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy-APEs#83]
I had suggested this as a Coordination meeting topic on astropy/astropy-project#255. But maybe we can save time by simply asking the question: is APE 13 still considered the current guidance on spectroscopy code development, or are substantial revisions needed?  Has it been superseded by another document?

I want to be able to point people from outside the Astropy community to that document or its equivalent. These people may be potential contributors to code development, so it's more than just for the purpose of satisfying a passing interest.

As the contributors to APE 13: @kelle @eteq @pllim

**Comment by pllim** [comment]
For the record, I never contributed to that APE (if I did, I have no recollection and probably not in a significant way). The authors on the record are @crawfordsm , @nmearl , @keflavich , and @eteq .

**Comment by weaverba137** [comment]
Fair enough, but at the top of [APE 13](https://github.com/astropy/astropy-APEs/blob/main/APE13.rst) those are the three contributors.

**Comment by dhomeier** [comment]
That would probably be because the actual document had been developed largely as [APE_specutil](https://github.com/astropy/astropy-APEs/commits/9d1ea533db9694a388c14412ea870f10516f52f9/APE_specutil.rst?browsing_rename_history=true&new_path=APE13.rst&original_branch=main).

**Comment by crawfordsm** [comment]
Just dropping by to say that it might be worthwhile to bring in @tepickering for comment as to the status of [specreduce](https://github.com/astropy/specreduce).

**Comment by tepickering** [comment]
APE 13 still looks accurate w.r.t. its mentions of specreduce and its scope. development of specreduce has finally picked up some steam and significant progress is being made.

**Comment by pllim** [comment]
At Astropy Coordination Meeting 2023, @eteq said APE 13 would be "current" again if we apply a minor update, particularly removing mention of visualization tool.
