### ISSUE TITLE
Broken link in APE0

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy-APEs#88]
There are many links to "Voting Members", with the form
```
`Voting Members <votingmembers>`_
```
but the file `votingmembers` doesn't exist. Has this been moved elsewhere?

**Comment by weaverba137** [comment]
Hmm, actually, this may be an issue with how GitHub renders APE0.  The raw RST file may actually be correct, but GitHub is interpreting that link as `https://github.com/astropy/astropy-APEs/blob/main/votingmembers`.

**Comment by pllim** [comment]
We could hardcode the URL but does that constitute a formal update to APE? 🤔

**Comment by weaverba137** [comment]
Good question. Seems like this could be classified as a typo to me.

**Comment by pllim** [comment]
Are you interested to submit a PR since you found the problem? Then you will be credited for the fix as well. Thanks!

**Comment by weaverba137** [comment]
Sure, I'll get one in soon.

**Comment by weaverba137** [comment]
I'm moving forward on the assumption that all links of the form
```
`Voting Members <votingmembers>`_
```
are meant to link to the *internal section* called "The Voting Members", rather than [the list of actual voting members](https://www.astropy.org/team.html#votingmembers).

**Comment by pllim** [comment]
Yes, I was thinking of https://github.com/astropy/astropy-APEs/blob/main/APE0.rst#the-voting-members
